### ISSUE TITLE
Obligatoriedad de la educación en la primera infancia

### ISSUE THREAD

**Issue by CamilaFal** [raulsperoni/resistencia.uy#13]
Estimadas/os, además de felicitarlas/os por la iniciativa, quería comentarles de un error sobre el que ya se ha discutido públicamente.
Decir que "Se elimina la obligatoriedad de la educación en la primera infancia" no es correcto, ya que si bien esa aclaración se incorpora en el Art. 140 de la LUC, la educación en primera infancia no era obligatoria tampoco en la Ley General de Educación del 2008. El Art. 7 de la LGE ya establecía que la educación comenzaba a ser obligatoria a partir de los 4 años y el Art. 127 de la LUC cambia la redacción pero conserva ese punto. Es decir, nunca fue obligatoria la educación entre 0 y 3 años, entiendo que plantear que la LUC elimina esa obligatoriedad desvía la atención de los cambios perjudiciales que efectivamente introduce esa Ley.

Gracias!
Saludos, Camila

**Comment by raulsperoni** [comment]
Hola! muchas gracias por el aporte! Se te ocurre una redacción alternativa para explicar ese cambio en palabras sencillas?

**Comment by ileanaoli** [comment]
Que no hubo cambio sustancial sería una opción que por lo menos no reflejaría una mentira.

**Comment by raulsperoni** [comment]
Estimadas gracias por el aporte! Pusimos una redacción alternativa en el comentario que creemos refleja mejor el cambio, y el porqué se busca derogarlo.
